############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Experiences"
url = "experiences/"
weight = 3



# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1
